import { StyleSheet } from 'react-native';
import { COLORS } from '../../theme/colors';

export const authStyles = StyleSheet.create({
  root: {
    flex: 1,
    paddingHorizontal: 22,
    backgroundColor: COLORS.bg,
  },
  scrollContent: {
    flexGrow: 1,
    width: '100%',
    maxWidth: 560,
    alignSelf: 'center',
    paddingTop: 18,
    paddingBottom: 36,
  },
  centeredContent: {
    flex: 1,
    width: '100%',
    maxWidth: 560,
    alignSelf: 'center',
    justifyContent: 'center',
    paddingBottom: 48,
  },
  topBar: {
    minHeight: 48,
    flexDirection: 'row',
    alignItems: 'center',
    marginHorizontal: -8,
  },
  topBarSide: {
    width: 48,
    height: 44,
    alignItems: 'center',
    justifyContent: 'center',
    borderRadius: 22,
  },
  topBarTitle: {
    flex: 1,
    textAlign: 'center',
    color: COLORS.text,
    fontFamily: 'Manrope_700Bold',
    fontSize: 15,
  },
  stepText: {
    color: COLORS.subtext,
    fontFamily: 'Manrope_700Bold',
    fontSize: 11,
    letterSpacing: 0.9,
    textTransform: 'uppercase',
    marginTop: 22,
    marginBottom: 10,
  },
  title: {
    fontFamily: 'Manrope_700Bold',
    fontSize: 30,
    lineHeight: 36,
    letterSpacing: -0.8,
    color: COLORS.text,
  },
  caption: {
    marginTop: 10,
    fontFamily: 'Manrope_400Regular',
    color: COLORS.subtext,
    fontSize: 15,
    lineHeight: 22,
  },
  inputLabel: {
    marginTop: 26,
    marginBottom: 8,
    color: COLORS.text,
    fontFamily: 'Manrope_700Bold',
    fontSize: 13,
  },
  input: {
    minHeight: 54,
    borderWidth: 1,
    borderColor: COLORS.border,
    borderRadius: 16,
    paddingHorizontal: 15,
    paddingVertical: 13,
    fontFamily: 'Manrope_600SemiBold',
    fontSize: 16,
    color: COLORS.text,
    backgroundColor: COLORS.bg,
  },
  inputFocused: {
    borderColor: COLORS.text,
  },
  inputError: {
    borderColor: '#b42318',
  },
  primaryButton: {
    minHeight: 54,
    marginTop: 18,
    backgroundColor: COLORS.primary,
    paddingHorizontal: 18,
    paddingVertical: 14,
    borderRadius: 17,
    alignItems: 'center',
    justifyContent: 'center',
  },
  primaryButtonDisabled: {
    opacity: 0.42,
  },
  primaryButtonText: {
    color: '#fff',
    fontFamily: 'Manrope_700Bold',
    fontSize: 15,
  },
  secondaryButton: {
    minHeight: 50,
    marginTop: 12,
    borderWidth: 1,
    borderColor: COLORS.border,
    borderRadius: 16,
    alignItems: 'center',
    justifyContent: 'center',
    paddingHorizontal: 16,
  },
  secondaryButtonText: {
    color: COLORS.text,
    fontFamily: 'Manrope_700Bold',
    fontSize: 14,
  },
  linkButton: {
    alignSelf: 'center',
    paddingHorizontal: 12,
    paddingVertical: 11,
    marginTop: 4,
  },
  linkText: {
    color: COLORS.text,
    fontFamily: 'Manrope_700Bold',
    fontSize: 14,
    textAlign: 'center',
  },
  helperText: {
    color: COLORS.subtext,
    fontFamily: 'Manrope_400Regular',
    fontSize: 12,
    lineHeight: 17,
    marginTop: 7,
  },
  errorText: {
    color: '#b42318',
    fontFamily: 'Manrope_600SemiBold',
    fontSize: 12,
    lineHeight: 17,
    marginTop: 7,
  },
  successText: {
    color: '#147a44',
    fontFamily: 'Manrope_600SemiBold',
    fontSize: 12,
    lineHeight: 17,
    marginTop: 7,
  },
  webNotice: {
    marginTop: 16,
    borderWidth: StyleSheet.hairlineWidth,
    borderColor: COLORS.border,
    borderRadius: 16,
    padding: 14,
    backgroundColor: '#f7f7f7',
  },
  contactRow: {
    flexDirection: 'row',
    alignItems: 'center',
    paddingVertical: 12,
    gap: 10,
    borderBottomWidth: StyleSheet.hairlineWidth,
    borderBottomColor: COLORS.divider,
  },
  contactName: {
    flex: 1,
    fontFamily: 'Manrope_600SemiBold',
    color: COLORS.text,
  },
  contactNumbers: {
    flex: 1,
    textAlign: 'right',
    fontFamily: 'Manrope_400Regular',
    color: COLORS.subtext,
    fontSize: 12,
  },
  checkbox: {
    width: 21,
    height: 21,
    borderRadius: 7,
    borderWidth: 1,
    borderColor: COLORS.border,
    alignItems: 'center',
    justifyContent: 'center',
    backgroundColor: '#fff',
  },
  checkboxOn: {
    backgroundColor: COLORS.primary,
    borderColor: COLORS.primary,
  },
});
