-- Circles Step 36C — recipient-only Whisper realtime pulses
--
-- `profile_whispers` deliberately remains RPC-only because it contains the
-- disappearing message body. Realtime needs a row-level signal to tell an
-- already-open recipient profile that it should refresh, so this table carries
-- only recipient + Whisper ids and no message content.

create table if not exists public.profile_whisper_pulses (
  id bigint generated by default as identity primary key,
  recipient_id uuid not null references public.users(id) on delete cascade,
  whisper_id uuid not null references public.profile_whispers(id) on delete cascade,
  created_at timestamptz not null default now(),
  constraint profile_whisper_pulses_whisper_unique unique (whisper_id)
);

create index if not exists profile_whisper_pulses_recipient_created_index
  on public.profile_whisper_pulses (recipient_id, created_at desc);

alter table public.profile_whisper_pulses enable row level security;

revoke all on table public.profile_whisper_pulses from anon, authenticated;
grant select on table public.profile_whisper_pulses to authenticated;

-- A pulse is visible only to its intended recipient. There is intentionally no
-- client INSERT/UPDATE/DELETE policy; the security-definer trigger writes it.
drop policy if exists "Recipients can read their Whisper realtime pulses"
  on public.profile_whisper_pulses;
create policy "Recipients can read their Whisper realtime pulses"
on public.profile_whisper_pulses
for select
to authenticated
using (recipient_id = auth.uid());

create or replace function public.emit_profile_whisper_realtime_pulse()
returns trigger
language plpgsql
security definer
set search_path = public
as $$
begin
  insert into public.profile_whisper_pulses (
    recipient_id,
    whisper_id,
    created_at
  )
  values (
    new.recipient_id,
    new.id,
    now()
  )
  on conflict (whisper_id) do nothing;

  return new;
end;
$$;

revoke all on function public.emit_profile_whisper_realtime_pulse() from public;

drop trigger if exists emit_profile_whisper_realtime_pulse_on_insert
  on public.profile_whispers;
create trigger emit_profile_whisper_realtime_pulse_on_insert
after insert on public.profile_whispers
for each row execute function public.emit_profile_whisper_realtime_pulse();

-- Supabase Realtime publication membership is installation-specific, so add
-- the signal table only when it is not already published.
do $$
begin
  if exists (
    select 1 from pg_publication where pubname = 'supabase_realtime'
  ) and not exists (
    select 1
    from pg_publication_tables
    where pubname = 'supabase_realtime'
      and schemaname = 'public'
      and tablename = 'profile_whisper_pulses'
  ) then
    alter publication supabase_realtime add table public.profile_whisper_pulses;
  end if;
end;
$$;

comment on table public.profile_whisper_pulses is
  'Recipient-only metadata pulses for realtime Whisper bubble refreshes. Contains no Whisper body/content.';
